# -*- lammps -*-
###
# Box and units  (use LJ units and periodic boundaries)
###

variable skin equal 0.4  # Sets the neighbor list skin distance (used to expand the cutoff radius).
variable every equal 5 # Determines how often the neighbor list is updated

units lj

atom_style bond 

boundary p p p

###
# Pair interactions require lists of neighbours to be calculated
###

neighbor ${skin} bin
neigh_modify every ${every} delay ${every} check yes

variable file_name equal 700  # 10, 20, ..., 100 atoms
variable ensemble equal replace_ensemble    #1, 2, 3, ..... 50 atoms
variable esp equal variable_esp

### READ "start" data file ###
read_data Polymer_Data_Initial.txt

######################



###
# Define groups (atom type 1 is group 'all')
###
group all type 1   # Determines how often the neighbor list is updated

###################################################################

###################################################################
# Pair interaction between non-bonded atoms
pair_style     lj/cut 1.12246152962189 
pair_modify     shift yes

# types 1 and 6 are chromatin, size 1 and correlationof velocity

pair_coeff 1 1 ${esp} 0.5 1.25


############################################################################
bond_style   harmonic 
special_bonds lj 0 1 1 #<=== I M P O R T A N T prevents LJ from being counted twice
# For style harmonic, specify:
#   * bond type
#   * K (energy/distance^2) 
#   * R0 (distance)
bond_coeff   1   30.0 0.6 



variable seed equal SEED_NUMBER
variable seed2 equal 2*${seed}+1234

#fix 1 dna nve   ###NVE ensemble
#fix 2 dna langevin   1.0 1.0 0.5  ${seed}
#fix 3 prots rigid molecule langevin/rotation 1.0 1.0 0.5 0.15 ${seed2}

fix 1 all nve                             # NVE integrator
fix 2 all langevin   1.0 1.0 1.0 ${seed}  # langevin thermostat

###################################################

###
# Output
###
variable t equal step


##### Sample thermodynamic info  (temperature, energy, pressure, etc.) #####
thermo 20000 #00
thermo_style   custom   step  temp  epair 
############################################################################

###
# set timestep of integrator
###
reset_timestep 0
timestep 0.005
# note this is smaller than usual - this is needed because we have proteins 
#                                   with size < 1

####################################################################################################



############################################################################
#### Set up a compute for R_g
compute myRG2compute all gyration
#### and write it to a file
variable RG2 equal c_myRG2compute
fix myRG2file all print 10000 "$t ${RG2}" file radius_of_gyration_squared.txt screen yes
############################################################################




##############
## before starting dumping run for 1.25 million steps
## to ensure we really do have an equilibrium configuration

## increase time step as much as possible
timestep 0.004  # so 1.25 million of these steps is like 5 million
## do the run
minimize 1e-4 1e-6 1000 100000
run 1000000


##############
## Now do the main production run of 5 million steps
## Dumping every 10^5 steps

reset_timestep 0
timestep 0.005


dump DUMPXYZ all xyz 10000 out_het.xyz

########################

compute msd_col all msd

fix msd_out all ave/time 1 1 1 c_msd_col[1] c_msd_col[2] c_msd_col[3] c_msd_col[4] file msd_output.txt



####################

#Compute cluster IDs for atoms

compute myCluster all cluster/atom 1.1
#Define chunks based on cluster IDs

compute myChunks all chunk/atom c_myCluster compress yes
#Compute the number of atoms in each chunk

compute sizeChunks all property/chunk myChunks count

fix chunkSizes all ave/time 5000000 1 5000000 c_sizeChunks file chunk_sizes_${ensemble}.dat mode vector


run 5000000

write_restart restart_file.restart

